### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by ojunio99** [CodePapa360/Convayto#1]
English: Yesterday
Portuguese: Ontem 

![image](https://github.com/user-attachments/assets/667e36b5-8d11-482c-b640-35b46181a54e)

**Comment by CodeWithAlamin** [comment]
Thank you for bringing this to my attention. Convayto currently supports only English and does not have built-in localization or translation features. Any translation occurring in your browser or through third-party tools is outside the scope of the app's functionality.

The issue you're experiencing with "Yesterday" not translating seems to be related to the translation tool you're using and not Convayto itself. I recommend reaching out to the support team of that tool for assistance.

Since this is not an issue with Convayto, I'll go ahead and close this ticket. If you have any other concerns or suggestions, feel free to share. Thank you for your understanding!
